plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  '@celo/connect@*':
    dependencies:
      '@celo/base': '*'
      'web3-eth-contract': '*'
      'web3-utils': '*'
  '@celo/contractkit@*':
    dependencies:
      'web3-utils': '*'
  '@celo/utils@*':
    dependencies:
      'randombytes': '*'
      'rlp': '*'
  '@ubeswap/sdk@*':
    dependencies:
      '@ethersproject/address': '*'
      '@ethersproject/solidity': '*'
      '@ethersproject/contracts': '*'
      '@ethersproject/networks': '*'
      '@ethersproject/providers': '*'
  "@ubeswap/hardhat-celo@*":
    dependencies:
      '@celo/contractkit': '*'
      '@nomiclabs/hardhat-ethers': '*'
  "@typechain/hardhat@*":
    dependencies:
      'lodash': '*'
      'typechain': '*'
  'typechain@*':
    dependencies:
      '@typechain/web3-v1': '*'

yarnPath: .yarn/releases/yarn-3.2.0-rc.5.cjs
